<?php

namespace Amirsahra\Illustrator\Facade;

use Illuminate\Support\Facades\Facade;

class Illustrator extends Facade
{
    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}